name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'

jobs:
  test-build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux
            run_test: true
            setup_env: |
              sudo apt-get update
              sudo apt-get install -f -y libegl1-mesa-dev
              sudo apt-get install -f -y mesa-vulkan-drivers
              rustup update
          - os: macos-latest
            name: Darwin
            run_test: false # macos vm doesn't have software metal api
            run_build: true
            setup_env: |
              rustup update
          - os: windows-latest
            name: Windows
            run_test: true
            setup_env: |
              rustup update
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Environment
        run: ${{ matrix.setup_env }}
        shell: bash
      - name: Set up cargo nexttest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - name: Set up cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: rust cargo tests
        if: matrix.run_test
        run: |
          cargo nextest run --status-level all --no-fail-fast 
      - name: rust cargo build
        if: matrix.run_build
        run: |
          cargo build
