use crate::*;

const I16_COMPARE_SHADER: &str = concat!(
    include_str!("../../../compute_shaders/i16/utils.wgsl"),
    include_str!("../compute_shaders/i16/cmp.wgsl")
);

//TODO
const I16_MIN_MAX_SHADER: &str = concat!(
    include_str!("../../../compute_shaders/i16/utils.wgsl"),
    include_str!("../compute_shaders/i16/cmp.wgsl")
);

impl CompareType for i16 {
    const COMPARE_SHADER: &'static str = I16_COMPARE_SHADER;
    const MIN_MAX_SHADER: &'static str = I16_MIN_MAX_SHADER;
}

#[cfg(test)]
mod test {
    use arrow_gpu_array::array::*;
    use arrow_gpu_test_macros::test_array_op;

    use crate::*;

    test_array_op!(
        test_gt_i16_array_i16,
        Int16ArrayGPU,
        Int16ArrayGPU,
        BooleanArrayGPU,
        gt,
        gt_dyn,
        [
            Some(0i16),
            Some(3),
            Some(3),
            Some(0),
            Some(3),
            None,
            None,
            Some(4),
            Some(40),
            Some(70)
        ],
        [
            Some(1i16),
            Some(2),
            Some(1i16),
            Some(2),
            Some(3),
            None,
            Some(4),
            None,
            Some(4),
            Some(7)
        ],
        [
            Some(false),
            Some(true),
            Some(true),
            Some(false),
            Some(false),
            None,
            None,
            None,
            Some(true),
            Some(true)
        ]
    );

    test_array_op!(
        test_all_gt_i16_array_i16,
        Int16ArrayGPU,
        Int16ArrayGPU,
        BooleanArrayGPU,
        gt,
        gt_dyn,
        [Some(100i16); 100],
        [Some(1i16); 100],
        [Some(true); 100]
    );

    test_array_op!(
        test_gteq_i16_array_i16,
        Int16ArrayGPU,
        Int16ArrayGPU,
        BooleanArrayGPU,
        gteq,
        gteq_dyn,
        [
            Some(0i16),
            Some(3),
            Some(3),
            Some(0),
            Some(3),
            None,
            None,
            Some(4),
            Some(40),
            Some(7)
        ],
        [
            Some(1i16),
            Some(2),
            Some(1),
            Some(2),
            Some(3),
            None,
            Some(4),
            None,
            Some(4),
            Some(7)
        ],
        [
            Some(false),
            Some(true),
            Some(true),
            Some(false),
            Some(true),
            None,
            None,
            None,
            Some(true),
            Some(true)
        ]
    );

    test_array_op!(
        test_lt_i16_array_i16,
        Int16ArrayGPU,
        Int16ArrayGPU,
        BooleanArrayGPU,
        lt,
        lt_dyn,
        [
            Some(0i16),
            Some(3),
            Some(3),
            Some(0),
            Some(3),
            None,
            None,
            Some(4),
            Some(40),
            Some(7)
        ],
        [
            Some(1i16),
            Some(2),
            Some(1),
            Some(2),
            Some(3),
            None,
            Some(4),
            None,
            Some(4),
            Some(7)
        ],
        [
            Some(true),
            Some(false),
            Some(false),
            Some(true),
            Some(false),
            None,
            None,
            None,
            Some(false),
            Some(false)
        ]
    );

    test_array_op!(
        test_lteq_i16_array_i16,
        Int16ArrayGPU,
        Int16ArrayGPU,
        BooleanArrayGPU,
        lteq,
        lteq_dyn,
        [
            Some(0i16),
            Some(3),
            Some(3),
            Some(0),
            Some(3),
            None,
            None,
            Some(4),
            Some(40),
            Some(7)
        ],
        [
            Some(1i16),
            Some(2),
            Some(1),
            Some(2),
            Some(3),
            None,
            Some(4),
            None,
            Some(4),
            Some(7)
        ],
        [
            Some(true),
            Some(false),
            Some(false),
            Some(true),
            Some(true),
            None,
            None,
            None,
            Some(false),
            Some(true)
        ]
    );

    test_array_op!(
        test_eq_i16_array_i16,
        Int16ArrayGPU,
        Int16ArrayGPU,
        BooleanArrayGPU,
        eq,
        eq_dyn,
        [
            Some(0i16),
            Some(3),
            Some(3),
            Some(0),
            Some(3),
            None,
            None,
            Some(4),
            Some(40),
            Some(7)
        ],
        [
            Some(1i16),
            Some(2),
            Some(1),
            Some(2),
            Some(3),
            None,
            Some(4),
            None,
            Some(4),
            Some(7)
        ],
        [
            Some(false),
            Some(false),
            Some(false),
            Some(false),
            Some(true),
            None,
            None,
            None,
            Some(false),
            Some(true)
        ]
    );
}
